on: [push, pull_request]

name: CI

jobs:
  node-jdbc:
    name: node-jdbc
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node_version:
          - 18
          - 20
        include:
          # Oracle
          - distribution: oracle
            java_version: 17
          - distribution: oracle
            java_version: 21
            new_drivers: true
          # Temurin
          - distribution: temurin
            java_version: 8
          - distribution: temurin
            java_version: 11
          - distribution: temurin
            java_version: 17
          - distribution: temurin
            java_version: 21
            new_drivers: true
          # Microsoft
          - distribution: microsoft
            java_version: 11
          - distribution: microsoft
            java_version: 17
          - distribution: microsoft
            java_version: 21
            new_drivers: true
          # Corretto
          - distribution: corretto
            java_version: 8
          - distribution: corretto
            java_version: 11
          - distribution: corretto
            java_version: 17
          - distribution: corretto
            java_version: 21
            new_drivers: true
          # Azul Zulu OpenJDK
          - distribution: zulu
            java_version: 8
          - distribution: zulu
            java_version: 11
          - distribution: zulu
            java_version: 17
          - distribution: zulu
            java_version: 21
            new_drivers: true
        arch:
          - x64
    steps:
      - name: ☑️ Checkout ☑️
        uses: actions/checkout@v4
      - name: ☕ Java ☕
        uses: actions/setup-java@v4
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java_version }}
      - name: 🐍 Python 🐍
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: 🔋 Node 🔋
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
      - name: 💾 Install 💾
        run: yarn install
      - name: Set up new drivers
        run: cp drivers-10.17/* drivers
        if: matrix.new_drivers
      - name: 🧪 Test (Node ${{ matrix.node_version }}, Java ${{ matrix.java_version }}, ${{ matrix.distribution }}) 🧪
        run: yarn test
