on: [push, pull_request]

name: CI

jobs:
  node-jdbc:
    name: node-jdbc
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node_version:
          - 18
          - 20
        distribution:
          - oracle
          - temurin
          - microsoft
          - corretto
          - zulu
        java_version:
          - 8
          - 11
          - 17
          - 21
        arch:
          - x64
        exclude:
          - distribution: oracle
            java_version: 8
          - distribution: oracle
            java_version: 11
          - distribution: microsoft
            java_version: 8
    steps:
      - name: ☑️ Checkout ☑️
        uses: actions/checkout@v4
      - name: ☕ Java ☕
        uses: actions/setup-java@v4
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java_version }}
      - name: 🐍 Python 🐍
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: 🔋 Node 🔋
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
      - name: 💾 Install 💾
        run: yarn install
      - name: Set up new drivers
        run: cp drivers-10.17/* drivers
        if: ${{ matrix.java_version > 20 }}
      - name: 🧪 Test (Node ${{ matrix.node_version }}, Java ${{ matrix.java_version }}, ${{ matrix.distribution }}) 🧪
        run: yarn test
